version: '3.8'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    ports:
      - "5500:5500"
    environment:
      - DB_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://server:5500
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge 
   